sudo: false
language: node_js
node_js:
- "6"
- "lts/*"

env:
  matrix:
  - BROWSER=chrome  BVER=stable
  - BROWSER=chrome  BVER=beta
  - BROWSER=chrome  BVER=unstable
  - BROWSER=firefox BVER=stable
  - BROWSER=firefox BVER=beta
  - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allowed_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
  - nathan+rtcio@coviu.com
